org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

mod_version=1.0
maven_group=acore.hack
archives_base_name=acorehack

# Minecraft and Fabric
minecraft_version=1.21
yarn_mappings=1.21+build.2
loader_version=0.15.11
fabric_version=0.96.4+1.21

# Satin version cho Minecraft 1.21
satin_version=1.12.0
