# Gradle settings
org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=512m
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true

# Mod properties
mod_version=1.0
maven_group=acore.hack
archives_base_name=acorehack

# Minecraft properties
minecraft_version=1.21
yarn_mappings=1.21+build.2
loader_version=0.15.11

# Dependencies
fabric_version=0.100.3+1.21
orbit_version=0.2.3
netty_version=4.1.90.Final
