name: Build Mira Client

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Mod
        run: ./gradlew build --no-daemon --stacktrace

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: Mira-Client
          path: build/libs/*.jar
